
token: TokenTimeIsBackBuddyss  # Lichess OAuth2 Token.

engines:
 # standard:
   # dir: "./engines"
  #  name: "lc0"
  #  ponder: true
 #   silence_stderr: false
   # move_overhead_multiplier: 9.5
 #   uci_options:
     # Threads: 4
    #  NNCacheSize: 400000
    #  MoveOverheadMS: 225
     # MinibatchSize: 4
     # Backend: "dnnl"
    #  MaxPrefetch: 5
     # WeightsFile: "./engines/791556.pb.gz"

     # UCI_Chess960: true 
  #  limits:
      # time: 20.0
      # depth: 50
      # nodes: 8000000
  standard: 
    dir: "./engines"
    name: "dragon-linux-avx2"
    ponder: true
    silence_stderr: false 
    move_overhead_multiplier: 10.7
    uci_options: 
      Threads: 4
      Hash: 4500
      Table Memory: 748
      Personality: "Defensive"
      #Dynamism: 130
      #MoveOverheadMS: 200
     # Backend: "dnnl"
    #  MiniBatchSize: 4 
    limits: 
  standard_human:
    dir: "./engines"
    name: "supranova"
    ponder: false
    silence_stderr: false
    move_overhead_multiplier: 2.0
    uci_options:
      Threads: 4
      Hash: 4096
    limits:

syzygy:
  standard:
    enabled: true
    paths:
      - "./engines/syzygy"
    max_pieces: 6
    instant_play: true
  antichess:
    enabled: false
    paths:
      - "/path/to/antichess/syzygy"
    max_pieces: 6
    instant_play: true
  atomic:
    enabled: false
    paths:
      - "/path/to/atomic/syzygy"
    max_pieces: 6
    instant_play: true

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

opening_books:
  enabled: true
  priority: 401
  books:
    standard_white_tournament:
      selection: best_move 
      allow_repetitions: true  
     # max_depth: 80
      names:
        - niki 
        - lilawhite
       # - Perfect2023
       # - Opimus3.1
        - optimus2502
       # - optimus4
      #  - Opimus3.1
      #  - noob
    standard_black_tournament:
      selection: best_move 
      allow_repetitions: true  
     # max depth : 45 
      names:
        - niki
      #  - optimus4
        - lilawhite
        - badwhite
     #   - Titans
      #  - Opimus3.1
       # - optimus4
        - optimus2502
    standard_human: 
      selection: best_move 
      allow_repetitions: false
      names: 
        - gm
      #  - noob
       # - Titans   
    chess960:
      selection: best_move
      allow_repetitions: true
      names:
        - chess960
    standard:
      selection: weighed_random
      allow_repetitions: false
      names:
        - komodo
    

online_moves:
 # dynamic_selection: true
  opening_explorer:
    enabled: true
    priority: 249
 #   player: Username
    only_without_book: false
    use_for_variants: true
    allow_repetitions: true 
    min_time: 20
    timeout: 5
    min_games: 10
    only_with_wins: true
    selection: "performance"
    anti: true
    # max_depth: 20

  lichess_cloud:
    enabled: false
    priority: 200
    only_without_book: true
    min_eval_depth: 20
    min_time: 10
    timeout: 3
    use_for_variants: false
    allow_repetitions: false       
    trust_eval: true 
    # max_depth: 30

  chessdb:
    enabled: true
    priority: 250
    only_without_book: false
    best_move: false
    min_time: 20
    timeout: 3
   # max_moves: 1
   # selection: "optimal"
    allow_repetitions: true      
    trust_eval: true 
    
    # max_depth: 30

  online_egtb:
    enabled: true
    min_time: 20
    timeout: 3

offer_draw:
  enabled: true
  score: 10
  consecutive_moves: 6
  min_game_length: 30
  against_humans: false
  min_rating: 2860
  use_for_variants: true

resign:
  enabled: true
  score: -1100
  consecutive_moves: 5
  against_humans: false
  min_rating: 3100
  use_for_variants: false

challenge:
  concurrency: 1
  bullet_with_increment_only: true
  max_takebacks: 2
  min_initial: 180
  max_initial: 1200
  variants:
    - standard
   # - chess960
   # - antichess
 #   - atomic
  #  - kingOfTheHill
  #  - racingKings
 #   - threeCheck
    - fromPosition
   # - crazyhouse
  bot_time_controls:
    - bullet
    - blitz
    - rapid
  #  - classical
  human_time_controls:
    - rapid
  bot_modes:
   # - casual
    - rated
  human_modes:
    #- casual
    - rated

matchmaking:
  delay: 676
  timeout: 30
  selection: cyclic
  types:
    bullet:
      tc: 4+0
      #variant: chess960
    bulle2:
      tc: 3+0
    bc:
      tc: 5+0
    bm3:
      tc: 3+1
    gulugulu:
      tc: 1+1
    guliguli:
      tc: 3+2
    hvj:
      tc: 3+3
    win:
      tc: 6+0
    loss:
      tc: 0.75+0
    drum:
      tc: 0.5+8
      variant: standard

messages:
  greeting: "Konnichiwa guzaimase! ❤️‍🔥Using help of {engine} embedded in {me} Type !help to glimpse my arsenal. Best of luck"
  goodbye: "GGs, ezz. May we meet again, may I win again 💶 {me} signing off!"
  greeting_spectators: "ITZ Supranova11.0.0 in {me} competing for more depth with @{opponent} Type !help for a list of commands."
  goodbye_spectators: "SIMULATION TERMINATED @{opponent}.May our paths cross again!?Thanks For watching, {me} signing off!"

whitelist:
  - Supratsa
  - Shreyashi-2016
blacklist:
 # - NimsiluBot
 # - VEER-OMEGA-BOT
online_blacklists:                        # List of URLs for online blacklists. One username per line.
books:
 # Titans: "./engines/black.bin"
  optimus2502: "./engines/Book3.bin"
 # optimus4: "./engines/win.bin"
 # Perfect2023: "./engines/white.bin"
 # Opimus3.1: "./engines/Optical.bin"
 # noob: "./engines/Titans.bin"
#  ai: "./engines/nikibook.bin"
  gm: "./engines/gm2001(1).bin"
  niki: "./engines/Book1.bin"
  lilawhite: "./engines/Book2.bin"
  lilablack: "./engines/lila.bin"
  badwhite: "./engines/badwhite.bin"
  chess960: "./engines/chess960.bin"
  komodo: "./engines/komodo.bin"
