name: Sync BotLi Files

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download exact BotLi versions of selected files
        run: |
          FILES=("lichess_game.py" "botli_dataclasses.py" "configs.py" "config.py")
          for FILE in "${FILES[@]}"; do
            curl -sSL "https://raw.githubusercontent.com/Torom/BotLi/main/$FILE" -o "$FILE"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lichess_game.py botli_dataclasses.py configs.py config.py
          git commit -m "Sync files with Torom/BotLi" || echo "No changes to commit"
          git push
