name: Sync lichessbot branch

on:
  workflow_dispatch: # allows manual trigger
  push:
    branches:
      - main # trigger when main is updated

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add upstream repo
        run: git remote add upstream https://github.com/Torom/BotLi.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Reset lichessbot branch to upstream
        run: |
          git checkout -B lichessbot
          git reset --hard upstream/main  # overwrite with upstream
          git push origin lichessbot --force
