name: Build Lichess Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install nuitka

      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev

      - name: Compile user_interface.py
        run: |
          python3 -m nuitka \
            --onefile \
            --output-dir=engines \
           --output-filename=user_interface \
           user_interface.py


      - name: List Build Output
        run: ls -la engines/

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: botli-linux
          path: engines/user_interface
