name: Build Lc0 DNNL CPU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ git libdnnl-dev

      - name: Clone Lc0 source
        run: |
          git clone --branch release/0.30.0 https://github.com/LeelaChessZero/lc0.git

      - name: Build Lc0 with DNNL
        run: |
          cd lc0
          mkdir build
          cd build
          cmake -DUSE_DNNL=1 ..
          make -j$(nproc)

      - name: Upload engine artifact
        uses: actions/upload-artifact@v4
        with:
          name: lc0-dnnl
          path: lc0/build/lc0
