name: Build lc0

on:
  workflow_dispatch:

jobs:
  build-lc0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ git libdnnl-dev wget

      - name: Clone lc0
        run: |
          git clone https://github.com/LeelaChessZero/lc0.git
          cd lc0
          git submodule update --init --recursive

      - name: Build lc0 (CPU DNNL)
        run: |
          mkdir -p lc0/build
          cd lc0/build
          cmake -DUSE_DNNL=ON -DUSE_OPENBLAS=OFF -DUSE_CUDA=OFF -DUSE_TENSORRT=OFF ..
          make -j$(nproc)

      - name: Prepare engines folder
        run: |
          mkdir -p engines
          cp lc0/build/lc0 engines/

      - name: Download small test network
        run: |
          mkdir -p engines/networks
          # Small fast network (~2MB)
          wget -O engines/networks/test.nnue https://training.lczero.org/get_network?sha=2c6a26c07d6d2e51d91d2dbd3a7b0e13b89e2b31c07b48b7f8c0a3c730f3a0a2
          echo "network file=engines/networks/test.nnue" > engines/lc0.config

      - name: Verify lc0
        run: |
          ./engines/lc0 --help
