name: Lint and AutoFix user_interface.py

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "user_interface.py"

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install tools
        run: |
          pip install pylint autopep8

      - name: Run pylint (report only)
        run: pylint user_interface.py || true

      - name: Run autopep8 (minimal changes)
        run: |
          # Only apply basic formatting, no aggressive changes
          autopep8 --in-place --max-line-length 120 user_interface.py

      - name: Commit changes to lichessbot branch
        run: |
          if ! git diff --exit-code; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git checkout -B lichessbot
            git add user_interface.py
            git commit -m "Auto-format user_interface.py with autopep8 (minimal changes)"
            git push origin lichessbot
          fi
