name: Ruff Auto-fix

on:
  push:
    branches:
      - libot
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: libot
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff (fix + format)
        run: |
          ruff check . --fix --config .ruff.toml || true
          ruff format . --config .ruff.toml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore(ruff): auto-fix linting issues"
            git push origin libot
          else
            echo "No changes to commit."
          fi
